# Generated by Django 3.1.7 on 2021-06-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
