# Generated by Django 3.1.7 on 2021-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
